spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      url: ${REDIS_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in prod

server:
  port: ${PORT:8080}

fluxpay:
  webhook:
    worker:
      enabled: true
